"""Root-owned frozen prompts and serial attempt allocation for the actual sample."""
from pathlib import Path
import sys,json
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'novel_to_comic_skills/scripts'))
import comic_pipeline as cp
root=Path(__file__).resolve().parent/'灯塔来信';project=cp.project_load(root)
refs=cp.load_json(root/'design/reference-index.json')
selection={
 'p01':['zhiwei-base'],'p02':['zhiwei-base','luyan-base'],
 'p03':['women-base','zhiwei-base','luyan-base'],'p04':['women-base'],
 'p05':['zhiwei-base'],'p06':['women-base','zhiwei-base'],
 'p07':['men-base','luyan-base'],'p08':['men-base'],
 'p09':['women-work'],'p10':['men-base','luyan-work'],
 'p11':['women-work','luyan-work'],'p12':['luyan-work','women-work'],
 'p13':['women-base','women-work'],'p14':['zhiwei-base','luyan-base'],
 'p15':['comparison','women-work'],'p16':['zhiwei-base','luyan-base']}
action={
 'p01':'One single medium-wide establishing shot: Zhiwei alone stepping inside the open RIGHT wooden doorway into the stone lighthouse workshop, holding a CLOSED small rectangular wooden carry box firmly with both hands at waist. Her refined face and complete green skirt/cardigan visible. Sea-facing window LEFT, worktable CENTER, archives BACK. No other people. Evening arrival, lens NOT visible because box closed.',
 'p02':'Two-person medium close scene at center worktable. On LEFT Zhiwei watches; on RIGHT Luyan supports the OPEN wooden carry box with both hands and studies the pale rounded-square glass lens inside. Tiny hairline at outer lens rim visible, not shattered. Both faces visible, composed male concern and attentive female expression. No installation or lit lamp yet. ONLY these two.',
 'p03':'Exactly three people in medium shot. Tangning (young woman from LEFT HALF of women-base sheet) has just removed an aged plain envelope from BACK archive shelf and turns presenting it, lively restrained expression. Zhiwei and Luyan at worktable calmly look towards her. Tangning wears beige blouse terracotta skirt, NO apron. NO older Zhou or extra people in frame. Envelope no legible writing.',
 'p04':'Exactly two women: LEFT Tangning (young left-half reference) holding the old plain envelope, RIGHT Zhou (elderly right-half reference) pauses in open RIGHT door with surprised hesitant recognition, gaze on envelope. Chest-up close framing, both distinct faces clearly readable, aged Zhou must retain wrinkles and plump physique, not beautified into young face.',
 'p05':'Zhiwei alone, beautiful refined EXACT side-profile face near LEFT window, eyes lowered to the unfolded old letter held naturally in two hands. Subtle emotional regret/attention, long oval feminine face, graceful shoulder/neck and black low tie. Ivory knitted shawl still ON. Camera close portrait plus readable hands/paper. Paper has NO visible letters or text. Sea evening light behind, no flashback or other people.',
 'p06':'Exactly two women at left window: older round plump Zhou on LEFT with gently lowered eyes speaks compassionately; elegant long-oval Zhiwei on RIGHT listens, eyebrows/hand relax, holding unfolded plain letter loosely. Medium-close waist-up both faces visible. Zhiwei still wears cardigan. Clear age/face/body difference. No other woman.',
 'p07':'Exactly two masculine men side by side at CENTER workbench, Xuchuan on LEFT (young square-face man from LEFT HALF men-base) points with one hand to EMPTY circular mounting groove at glass lens bronze base; tall refined Luyan on RIGHT studies that missing-ring location. Xuchuan gray rolled-sleeve work shirt, Luyan BLUE-GRAY shirt with sleeves DOWN. A toolbox rests by Xuchuan. Lens gently cracked at edge, MOUNTING RING MISSING at this stage, NOT repaired, no light. Both faces distinguishable.',
 'p08':'Exactly two men from men-base: aged stocky receding-hair Zhao on RIGHT has just placed an OPEN worn iron spare-parts box containing a few brass ring parts on table; square-jaw Xuchuan on LEFT watches it attentively. Both full faces, stocky aged man vs younger muscular man obvious. No Luyan. Zhao brown work jacket, Xuchuan gray shirt. Not an empty box yet.',
 'p09':'Exactly two clearly feminine women in complete-body medium scene by workshop chairs, matching women-work sheet exactly. Taller long-oval Zhiwei LEFT has already put on same GRAY apron as shorter round-faced bob-haired Tangning RIGHT. Zhiwei gently hangs her REMOVED ivory knitted shawl on chair back, hands anatomically correct. Both wear their ivory/beige blouses under apron and green/terracotta skirts, no cardigan on Zhiwei body. Face structures and heights distinct despite matching apron. No men/elders.',
 'p10':'Exactly two male engineers in side-view medium scene working together. LEFT shorter muscular square-faced Xuchuan from LEFT men-base bends slightly using screwdriver to tighten bronze ring onto same glass lens base. RIGHT taller slim angular-faced Luyan from luyan-work watches spirit level beside base, his exact side-profile face visible. Both gray work shirts and rolled cuffs, clearly different jaw/brows/neck/torso. Glass hand-sized, matching prop, NOT glowing. No extra people.',
 'p11':'Exactly three people, medium close action with faces and anatomical hands visible. Zhiwei LEFT and Luyan RIGHT carefully LOWER the SAME one hand-sized rounded-square glass optical lens into its single bronze mounting socket on table/lamp base. Zhiwei BOTH hands cradle lens; Luyan one hand steadies metal socket, his other hand supports edge. No duplicated lenses or extra arms. Tangning behind center (young RIGHT HALF of women-work) records positioning on plain unlettered paper, attentive. All work outfits: both women gray aprons NO shawl, Luyan gray rolled-sleeve shirt. Lamp is OFF at this exact moment. No light beam yet.',
 'p12':'Exactly two main leads in work outfits. Luyan LEFT has just CLOSED a simple wall-mounted electrical lever switch, one hand on lever, face shows subtle pleased smile; Zhiwei RIGHT lifts her head towards warm newly lit lamp with joyful relieved eyes. Same mounted glass optical component visible on lamp base, warm light now illuminating faces and a beam visible through window across sea. Medium scene, clear female and male faces. No other woman/worker, no text.',
 'p13':'Exactly two women. Elderly plump gray-curled Zhou sits LEFT at wooden desk with a pen in her RIGHT hand touching plain unfolded letter paper, seriously and warmly writing a reply. Younger round-faced brown-bob Tangning stands RIGHT beside her calmly, STILL wearing gray work APRON over beige blouse and terracotta skirt, corresponding RIGHT HALF of women-work not Zhiwei. NO actual letters, words or glyphs on paper. Medium-close view, Zhou aged feminine face and Tangning distinct young feminine face visible. Warm night lamplight. No third person.',
 'p14':'Exactly two main leads in BASE outfits at LEFT sea window. Refined feminine Zhiwei on LEFT in ivory blouse/green skirt/ivory knitted shawl holds the CLOSED wooden carry box at waist; masculine tall Luyan on RIGHT now BLUE-GRAY shirt with sleeves DOWN. Both side-profile faces distinct and correctly matching refs, quiet relieved expressions. Warm lamp from inside, cool blue night sea outside. Medium half-body, no work apron or gray work shirt, no extra people.',
 'p15':'Exactly SIX named adults together inside workshop near RIGHT open door, medium-wide enough to show individual faces AND actions; do not add or omit a person. LEFT to RIGHT: Zhiwei (green skirt ivory cardigan) holding OPEN empty wooden carry box; Zhou elderly graybluecoat gently placing a folded plain reply letter INTO that wooden box; Tangning young short roundface/brown bob in GRAY APRON waves toward leaving workers; tall handsome Luyan bluegray sleeves-down shirt stands behind Zhiwei; square muscular Xuchuan grayshirt holds his TOOLBOX; aged stocky Zhao brownjacket holds EMPTY ironbox. Use six-person comparison sheet for exact six base faces, but Tangning uses RIGHT HALF women-work for her current gray apron (IGNORE left work Zhiwei). Zhiwei remains BASE cardigan, not apron. All age/face/physique differences clearly readable. Warm peaceful night. No textual markings.',
 'p16':'Exactly Zhiwei and Luyan in BASE outfits, full-body medium-wide exterior scene walking side by side DOWN stone steps from a modest old coastal lighthouse at blue night. Zhiwei LEFT ivory knit shawl/green skirt, calm gently open lips as if speaking; Luyan RIGHT bluegray sleeves-down shirt/dark trousers, slight warm smile listening, taller slender masculine body. Preserve both matching refined faces (large enough readable) and graceful distinct female/male silhouettes. Lighthouse and tranquil sea BEHIND them, soft warm beam out towards sea. No other people, empty hands, no new plot props.'}
characters={c['id']:c for c in project['script']['characters']}
queue=[]
for panel in project['script']['panels']:
    pid=panel['id'];binding={'appearance_versions':panel['appearance_versions'],'reference_ids':[refs[s] for s in selection[pid]]}
    bind_path=root/'design/panel-bindings'/(pid+'.json');cp.atomic_json(bind_path,binding)
    cp.run(cp.parser().parse_args(['bind-panel','--project',str(root),'--panel',pid,'--bindings',str(bind_path)]))
    project=cp.project_load(root)
    selected=cp.select_references(root,project,panel)
    image_paths=[str(cp.inside(root,r['path'])) for r in selected]
    if pid!='p16':image_paths.append(str(root/'art/raw/workshop.png'))
    roles=[]
    for index,(stem,reference) in enumerate(zip(selection[pid],selected),1):
        roles.append(f'Image {index} ({stem}) = '+json.dumps(reference['subjects'],ensure_ascii=False))
    if pid!='p16':roles.append(f'Image {len(image_paths)} = workshop layout and props ONLY; do not output its model-sheet insets. Missing ring/box contents determined by this action, not generic reference state.')
    prompt=('Use case: illustration-story. Output ONE single continuous full-color story comic PANEL, landscape 3:2 canvas, NOT a model sheet, montage, grid or page. Same precise refined illustrated manga style, subtle clean contours, softly shaded warm ivory/sea-gray colors as these validated reference images; not photo.\n'
            +'Reference roles:\n'+'\n'.join(roles)+'\n'
            +'Action and framing (one simultaneous instant): '+action[pid]+'\n'
            +'Identity constraints for ONLY these present people: '+json.dumps({cid:{'name':characters[cid]['name'],'gender':characters[cid]['appearance']['gender_presentation'],'identity_card':characters[cid]['identity_card'],'version':panel['appearance_versions'][cid]} for cid in panel['cast']},ensure_ascii=False)+'\n'
            +'Keep exact individual faces, body silhouettes, age, gender presentation and costume versions. Women unmistakably feminine faces/shoulders/body, men unmistakably masculine bone structure/shoulders. Leads remain finely designed and refined, background people natural and properly drawn. Correct hands/arms, no merged people or cloned faces. Paper/envelope blank and unlettered. No dialogue, captions, speech bubbles, labels, characters, signage, watermark, page borders or inset portraits. Fill one continuous narrative scene; final dialogue will be typeset separately. Do not imitate reference-sheet layout. Important faces/actions comfortably within canvas, no critical clipping.')
    prompt_path=root/'prompts/production'/(pid+'-a1.txt');prompt_path.parent.mkdir(parents=True,exist_ok=True);prompt_path.write_text(prompt,encoding='utf-8')
    result=cp.run(cp.parser().parse_args(['begin-panel','--project',str(root),'--panel',pid,'--prompt',str(prompt_path)]))
    queue.append({'panel_id':pid,'attempt':result['attempt'],'prompt_path':str(prompt_path),'referenced_image_paths':image_paths,
                  'output_path':str(root/'art/raw'/(pid+'-a1.png')),'tool_record_path':str(root/'reports/tool-executions'/(pid+'-a1.json')),
                  'script_hash':project['script_lock']['script_hash']})
cp.atomic_json(root/'scripts/drawing-queue.json',queue)
print({'allocated_panels':len(queue),'pending_attempts':len(queue),'references':len(project['art']['references'])})
